set_property SRC_FILE_INFO {cfile:C:/FPGA/FPGA_FUN/GraviTris/GraviTris.srcs/constrs_1/new/const.xdc rfile:../../../GraviTris.srcs/constrs_1/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {dbg_out[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {dbg_out[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {dbg_out[2]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {dbg_out[3]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {tftData_out[0]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {tftData_out[1]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {tftData_out[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {tftData_out[3]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {tftData_out[4]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {tftData_out[5]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {tftData_out[6]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {tftData_out[7]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports dbg_SW]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports dbg_LED0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports dbg_LED1]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports dbg_LED2]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports DC_out]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports WRX_out]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[23]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[12]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[4]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[6]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[21]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[28]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[14]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[9]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[12]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[20]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[27]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[15]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[7]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[30]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[16]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[18]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[25]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[31]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[2]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[3]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[26]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[31]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[4]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[10]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[21]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[22]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[26]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[17]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[8]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[10]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[1]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[18]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[5]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[23]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[6]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[28]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[29]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[30]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[2]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[29]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[24]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[0]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[11]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[16]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[22]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[25]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[15]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[24]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[20]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[13]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[14]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[8]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[7]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[13]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[3]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[9]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[5]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[19]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[0]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[11]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[17]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[19]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio_io_o[1]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_gpio_0/gpio2_io_o[27]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_gpio_0/gpio_io_o[0]} {design_1_i/axi_gpio_0/gpio_io_o[1]} {design_1_i/axi_gpio_0/gpio_io_o[2]} {design_1_i/axi_gpio_0/gpio_io_o[3]} {design_1_i/axi_gpio_0/gpio_io_o[4]} {design_1_i/axi_gpio_0/gpio_io_o[5]} {design_1_i/axi_gpio_0/gpio_io_o[6]} {design_1_i/axi_gpio_0/gpio_io_o[7]} {design_1_i/axi_gpio_0/gpio_io_o[8]} {design_1_i/axi_gpio_0/gpio_io_o[9]} {design_1_i/axi_gpio_0/gpio_io_o[10]} {design_1_i/axi_gpio_0/gpio_io_o[11]} {design_1_i/axi_gpio_0/gpio_io_o[12]} {design_1_i/axi_gpio_0/gpio_io_o[13]} {design_1_i/axi_gpio_0/gpio_io_o[14]} {design_1_i/axi_gpio_0/gpio_io_o[15]} {design_1_i/axi_gpio_0/gpio_io_o[16]} {design_1_i/axi_gpio_0/gpio_io_o[17]} {design_1_i/axi_gpio_0/gpio_io_o[18]} {design_1_i/axi_gpio_0/gpio_io_o[19]} {design_1_i/axi_gpio_0/gpio_io_o[20]} {design_1_i/axi_gpio_0/gpio_io_o[21]} {design_1_i/axi_gpio_0/gpio_io_o[22]} {design_1_i/axi_gpio_0/gpio_io_o[23]} {design_1_i/axi_gpio_0/gpio_io_o[24]} {design_1_i/axi_gpio_0/gpio_io_o[25]} {design_1_i/axi_gpio_0/gpio_io_o[26]} {design_1_i/axi_gpio_0/gpio_io_o[27]} {design_1_i/axi_gpio_0/gpio_io_o[28]} {design_1_i/axi_gpio_0/gpio_io_o[29]} {design_1_i/axi_gpio_0/gpio_io_o[30]} {design_1_i/axi_gpio_0/gpio_io_o[31]}]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_gpio_0/gpio2_io_o[0]} {design_1_i/axi_gpio_0/gpio2_io_o[1]} {design_1_i/axi_gpio_0/gpio2_io_o[2]} {design_1_i/axi_gpio_0/gpio2_io_o[3]} {design_1_i/axi_gpio_0/gpio2_io_o[4]} {design_1_i/axi_gpio_0/gpio2_io_o[5]} {design_1_i/axi_gpio_0/gpio2_io_o[6]} {design_1_i/axi_gpio_0/gpio2_io_o[7]} {design_1_i/axi_gpio_0/gpio2_io_o[8]} {design_1_i/axi_gpio_0/gpio2_io_o[9]} {design_1_i/axi_gpio_0/gpio2_io_o[10]} {design_1_i/axi_gpio_0/gpio2_io_o[11]} {design_1_i/axi_gpio_0/gpio2_io_o[12]} {design_1_i/axi_gpio_0/gpio2_io_o[13]} {design_1_i/axi_gpio_0/gpio2_io_o[14]} {design_1_i/axi_gpio_0/gpio2_io_o[15]} {design_1_i/axi_gpio_0/gpio2_io_o[16]} {design_1_i/axi_gpio_0/gpio2_io_o[17]} {design_1_i/axi_gpio_0/gpio2_io_o[18]} {design_1_i/axi_gpio_0/gpio2_io_o[19]} {design_1_i/axi_gpio_0/gpio2_io_o[20]} {design_1_i/axi_gpio_0/gpio2_io_o[21]} {design_1_i/axi_gpio_0/gpio2_io_o[22]} {design_1_i/axi_gpio_0/gpio2_io_o[23]} {design_1_i/axi_gpio_0/gpio2_io_o[24]} {design_1_i/axi_gpio_0/gpio2_io_o[25]} {design_1_i/axi_gpio_0/gpio2_io_o[26]} {design_1_i/axi_gpio_0/gpio2_io_o[27]} {design_1_i/axi_gpio_0/gpio2_io_o[28]} {design_1_i/axi_gpio_0/gpio2_io_o[29]} {design_1_i/axi_gpio_0/gpio2_io_o[30]} {design_1_i/axi_gpio_0/gpio2_io_o[31]}]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
